name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - "ci-212"
          - "ci-213"
          - "ci-3"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:8
      - run: sbt ${{ matrix.command }}
  jdk11_212:
    name: JDK11/scala_2.12 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
      - run: sbt ci-212
  jdk11_213:
    name: JDK11/scala_2.13 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
      - run: sbt ci-213

  jdk17_213:
    name: JDK17/scala_2.13 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
      - run: sbt ci-213

  windows_213:
    name: Windows/scala_2.13 tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
      - run: sbt ci-213-windows
        shell: bash
  checks:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
      - run: sbt "scalafixAll --check"
      - run: ./bin/scalafmt --test
  mima:
    name: Version Policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
      - run: sbt versionPolicyCheck
